[project]
name = "pyforge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Charles Azam", email = "azamcharles0@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
pyforge = "pyforge:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
